#!/usr/bin/env python3
from pathlib import Path
import sys

P = Path('flask_app.py')
START = '        function renderSettings() {'
END = '        function shareVipApp(pid, name) {'

NEW = r'''        function renderSettings() {
            if(!IS_MASTER) return '';
            ensureDataStruct();
            // SETUP_CONTROL_CENTER_V2_COMPACT
            const setup = appState.settings?.setup || {};
            const tr = Object.assign({dayBoundaryTime:'06:00',acceptBeforeMarketTime:true,rejectAfterMarketTime:true,dailyRepeatSchedule:true,separateOpenCloseStage:true}, setup.timeRules || {});
            const sc = Object.assign({autoScrapeEnabled:true,scrapeIntervalMinutes:5,confirmCount:2,ignoreOldFullResult:true,openFormatHelper:'123-4',closeFormatHelper:'123-45-678'}, setup.scrapeSettings || {});
            window.setupPanel = window.setupPanel || localStorage.getItem('tn_setup_panel') || 'market';
            window.setupSubPanel = window.setupSubPanel || localStorage.getItem('tn_setup_sub_panel') || 'ank';
            window.openSetupPanel = function(x){ window.setupPanel=x; localStorage.setItem('tn_setup_panel',x); render(true); };
            window.openSetupSubPanel = function(x){ window.setupSubPanel=x; localStorage.setItem('tn_setup_sub_panel',x); render(true); };
            window.saveSetupRulesCompact = async function(){
                const body = {auditAction:'setup_save', setup:{timeRules:{dayBoundaryTime:document.getElementById('setup-day-boundary')?.value||'06:00',acceptBeforeMarketTime:!!document.getElementById('setup-accept-before')?.checked,rejectAfterMarketTime:!!document.getElementById('setup-reject-after')?.checked,dailyRepeatSchedule:!!document.getElementById('setup-daily-repeat')?.checked,separateOpenCloseStage:!!document.getElementById('setup-stage-split')?.checked}, scrapeSettings:{autoScrapeEnabled:!!document.getElementById('setup-auto-scrape')?.checked,scrapeIntervalMinutes:parseInt(document.getElementById('setup-scrape-interval')?.value||'5',10)||5,confirmCount:parseInt(document.getElementById('setup-confirm-count')?.value||'2',10)||2,ignoreOldFullResult:!!document.getElementById('setup-ignore-old')?.checked,openFormatHelper:document.getElementById('setup-open-format')?.value||'123-4',closeFormatHelper:document.getElementById('setup-close-format')?.value||'123-45-678'}}};
                try{ const r=await fetch('/api/setup/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json(); if(d.status!=='success') throw new Error(d.message||'Save failed'); appState.settings=appState.settings||{}; appState.settings.setup=d.setup||body.setup; showRealNotification('✅ Setup Saved','Rules Firebase me save ho gaya.','success'); }
                catch(e){ showRealNotification('❌ Setup Error',String(e.message||e),'danger'); }
            };
            const bm = activeMarketsList(baseMarkets);
            const cap = parseFloat(state.config.capital)||0;
            const dayTgt = parseFloat(state.config.dayTarget)||0;
            const dayPL = globalStats.ank.pl + globalStats.jodi.pl + globalStats.pannel.pl;
            const dayPct = dayTgt>0 ? Math.min(100, Math.round((dayPL/dayTgt)*100)) : 0;
            const panelBtn = (key, icon, title, sub) => `<button onclick="openSetupPanel('${key}')" class="${window.setupPanel===key?'bg-[rgba(42,171,238,0.18)] border-[rgba(42,171,238,0.45)] text-white':'bg-[var(--surface-light)] border-[var(--border)] text-[var(--text-muted)]'} border rounded-2xl p-3 text-left active:scale-95"><i class="fas ${icon} ${window.setupPanel===key?'text-[var(--primary)]':''} mr-1"></i><b class="text-[10px] uppercase">${title}</b><p class="text-[8px] font-bold opacity-70 mt-1">${sub}</p></button>`;
            const sw = (id,on,title,note) => `<label class="flex items-center justify-between gap-3 bg-[var(--surface-light)] border border-[var(--border)] rounded-xl p-3"><span><b class="block text-white text-[10px] uppercase">${title}</b><small class="block text-[8px] text-[var(--text-muted)]">${note}</small></span><span class="switch m-0 shrink-0"><input id="${id}" type="checkbox" ${on?'checked':''}><span class="slider"></span></span></label>`;
            const marketPanel = () => `<div class="space-y-3">
                <div class="native-card p-4" style="border-color:rgba(0,194,111,0.28);background:rgba(0,194,111,0.04)">
                    <div class="flex items-center justify-between mb-3"><div><h3 class="text-white font-black text-[13px] uppercase"><i class="fas fa-plus text-[var(--green)] mr-1"></i>Add / Save Market</h3><p class="text-[9px] text-[var(--text-muted)]">Ek market add karo, app ke sab modules me sync hoga.</p></div><span class="text-[8px] text-[var(--green)] border border-[rgba(0,194,111,0.25)] rounded-lg px-2 py-1 font-black">LIVE</span></div>
                    <div class="grid grid-cols-2 gap-2"><div class="col-span-2"><p class="stat-lbl">Market Name</p><input id="setup-add-market-name" class="native-input text-[12px]" placeholder="TEST BAZAR"></div><div><p class="stat-lbl">Open</p><input id="setup-add-open-time" type="time" class="native-input text-[12px]"></div><div><p class="stat-lbl">Close</p><input id="setup-add-close-time" type="time" class="native-input text-[12px]"></div><div class="col-span-2"><p class="stat-lbl">Result URL</p><input id="setup-add-result-url" class="native-input text-[12px]" placeholder="https://dpbosse.net/jodi/TESTBAZAR/999"></div></div>
                    <div class="grid grid-cols-3 gap-2 my-3"><label class="bg-[var(--surface-light)] border border-[var(--border)] rounded-xl p-2 text-[9px] font-black text-white flex items-center justify-center gap-2"><input id="setup-add-enabled" type="checkbox" checked>Active</label><label class="bg-[var(--surface-light)] border border-[var(--border)] rounded-xl p-2 text-[9px] font-black text-white flex items-center justify-center gap-2"><input id="setup-add-scrape" type="checkbox" checked>Scrape</label><label class="bg-[var(--surface-light)] border border-[var(--border)] rounded-xl p-2 text-[9px] font-black text-white flex items-center justify-center gap-2"><input id="setup-add-forward" type="checkbox" checked>Forward</label></div>
                    <button onclick="addSetupMarket()" class="w-full bg-[var(--green)] text-white py-3 rounded-xl font-black text-[10px] uppercase active:scale-95"><i class="fas fa-save mr-1"></i>Save Market</button>
                </div>
                <div class="native-card p-4" style="border-color:rgba(255,59,48,0.35);background:rgba(255,59,48,0.05)"><h3 class="text-white font-black text-[13px] uppercase mb-1"><i class="fas fa-trash text-[var(--rose)] mr-1"></i>Delete Market</h3><p class="text-[9px] text-[var(--text-muted)] mb-3">Market + OPEN/CLOSE aliases all modules se remove honge.</p><div class="grid grid-cols-[1fr_auto] gap-2 items-end"><select id="setup-delete-market" class="native-input text-[12px]"><option value="">Select market</option>${bm.map(m=>`<option value="${m.n}">${m.n}</option>`).join('')}</select><button onclick="hardDeleteMarketFromSetup()" class="bg-[var(--rose)] text-white px-4 py-3 rounded-xl font-black text-[10px] uppercase active:scale-95"><i class="fas fa-trash"></i></button></div></div>
            </div>`;
            const openClosePanel = (title, color, dict) => { const all=bm.every(x=>state.dayRecords[currentDate][dict][x.n+' OPEN']!==false && state.dayRecords[currentDate][dict][x.n+' CLOSE']!==false); return `<div class="native-card p-4"><div class="flex items-center justify-between mb-3"><div><h3 class="text-[12px] font-black ${color} uppercase">${title}</h3><p class="text-[9px] text-[var(--text-muted)]">Open / Close individual switch</p></div><label class="flex items-center gap-2 text-[9px] font-black text-white uppercase">All <span class="switch scale-[0.65] m-0"><input type="checkbox" onchange="toggleAllMarketsOpenClose('${dict}',this.checked)" ${all?'checked':''}><span class="slider"></span></span></label></div><div class="grid grid-cols-1 gap-1.5 max-h-[58vh] overflow-y-auto pr-1">${bm.map(x=>{ const ok=x.n+' OPEN', ck=x.n+' CLOSE', oo=state.dayRecords[currentDate][dict][ok]!==false, co=state.dayRecords[currentDate][dict][ck]!==false; return `<div class="grid grid-cols-[1fr_auto_auto] gap-2 items-center bg-[var(--surface-light)] border border-[var(--border)] rounded-xl px-3 py-2"><span class="text-[9px] font-black text-white uppercase truncate">${x.n}</span><label class="flex items-center gap-1 text-[8px] text-[var(--primary)] font-black uppercase">Open <span class="switch scale-[0.55] m-0"><input type="checkbox" onchange="toggleMarketVis('${dict}','${ok}',this.checked)" ${oo?'checked':''}><span class="slider"></span></span></label><label class="flex items-center gap-1 text-[8px] text-[var(--amber)] font-black uppercase">Close <span class="switch scale-[0.55] m-0"><input type="checkbox" onchange="toggleMarketVis('${dict}','${ck}',this.checked)" ${co?'checked':''}><span class="slider"></span></span></label></div>`;}).join('')}</div></div>`; };
            const jodiPanel = () => { const all=bm.every(x=>state.dayRecords[currentDate].visJodi[x.n]!==false); return `<div class="native-card p-4"><div class="flex items-center justify-between mb-3"><div><h3 class="text-[12px] font-black text-[#B85CFF] uppercase">Jodi Markets</h3><p class="text-[9px] text-[var(--text-muted)]">Single switch per market</p></div><label class="flex items-center gap-2 text-[9px] font-black text-white uppercase">All <span class="switch scale-[0.65] m-0"><input type="checkbox" onchange="toggleAllMarkets('visJodi',this.checked)" ${all?'checked':''}><span class="slider"></span></span></label></div><div class="grid grid-cols-2 gap-2 max-h-[58vh] overflow-y-auto pr-1">${bm.map(x=>`<div class="flex items-center justify-between bg-[var(--surface-light)] border border-[var(--border)] rounded-xl p-2.5"><span class="text-[9px] font-black text-white uppercase truncate">${x.n}</span><span class="switch scale-[0.55] m-0"><input type="checkbox" onchange="toggleMarketVis('visJodi','${x.n}',this.checked)" ${state.dayRecords[currentDate].visJodi[x.n]!==false?'checked':''}><span class="slider"></span></span></div>`).join('')}</div></div>`; };
            const visibilityPanel = () => `<div class="space-y-3"><div class="grid grid-cols-3 gap-2"><button onclick="openSetupSubPanel('ank')" class="${window.setupSubPanel==='ank'?'bg-[rgba(42,171,238,0.18)] text-[var(--primary)] border-[rgba(42,171,238,0.35)]':'bg-[var(--surface-light)] text-[var(--text-muted)] border-[var(--border)]'} border rounded-xl py-2 font-black text-[10px] uppercase">ANK</button><button onclick="openSetupSubPanel('jodi')" class="${window.setupSubPanel==='jodi'?'bg-[rgba(184,92,255,0.18)] text-[#B85CFF] border-[rgba(184,92,255,0.35)]':'bg-[var(--surface-light)] text-[var(--text-muted)] border-[var(--border)]'} border rounded-xl py-2 font-black text-[10px] uppercase">JODI</button><button onclick="openSetupSubPanel('pan')" class="${window.setupSubPanel==='pan'?'bg-[rgba(250,199,72,0.18)] text-[var(--amber)] border-[rgba(250,199,72,0.35)]':'bg-[var(--surface-light)] text-[var(--text-muted)] border-[var(--border)]'} border rounded-xl py-2 font-black text-[10px] uppercase">PAN</button></div>${window.setupSubPanel==='ank'?openClosePanel('Ank Markets','text-[var(--primary)]','visAnk'):(window.setupSubPanel==='jodi'?jodiPanel():openClosePanel('Pan Markets','text-[var(--amber)]','visPan'))}<button onclick="saveMaster(false)" class="w-full bg-[var(--green)] text-white py-3 rounded-xl font-black text-[10px] uppercase active:scale-95"><i class="fas fa-save mr-1"></i>Save Visibility</button></div>`;
            const proto = (type,title,color) => `<div class="native-card p-4"><h3 class="text-[12px] font-black ${color} uppercase mb-3">${title}</h3><div class="grid grid-cols-2 gap-2"><div><p class="stat-lbl">Capital Cap</p><input type="number" inputmode="numeric" oninput="state.config.${type}.cap=parseFloat(this.value)||0;runLiveSync();autoSave();" value="${state.config[type].cap}" class="native-input text-sm py-3"></div><div><p class="stat-lbl">Target / Card</p><input type="number" inputmode="numeric" oninput="state.config.${type}.tgt=parseFloat(this.value)||0;runLiveSync();autoSave();" value="${state.config[type].tgt}" class="native-input text-sm py-3"></div></div></div>`;
            const moneyPanel = () => `<div class="space-y-3"><div class="native-card p-4" style="border-color:rgba(0,194,111,0.25);background:rgba(0,194,111,0.04)"><h3 class="text-[12px] font-black text-[var(--green)] uppercase mb-3"><i class="fas fa-coins mr-1"></i>Capital & Day Target</h3><div class="grid grid-cols-2 gap-2 mb-3"><div><p class="stat-lbl">Capital ₹</p><input type="number" inputmode="numeric" oninput="state.config.capital=parseFloat(this.value)||0;autoSave();" value="${cap}" class="native-input text-sm py-3 text-[var(--green)]"></div><div><p class="stat-lbl">Day Target ₹</p><input type="number" inputmode="numeric" oninput="state.config.dayTarget=parseFloat(this.value)||0;autoSave();" value="${dayTgt}" class="native-input text-sm py-3 text-[var(--primary)]"></div></div>${dayTgt>0?`<div><div class="flex justify-between mb-1"><span class="text-[9px] text-[var(--text-muted)] font-bold uppercase">Today</span><span class="text-[9px] font-black ${dayPL>=0?'text-[var(--green)]':'text-[var(--rose)]'}">${dayPL>=0?'+':''}₹${dayPL.toLocaleString()} / ₹${dayTgt.toLocaleString()}</span></div><div class="h-2 bg-[var(--surface-light)] rounded-full overflow-hidden"><div class="h-full rounded-full" style="width:${Math.max(0,dayPct)}%;background:${dayPL>=0?'var(--green)':'var(--rose)'}"></div></div></div>`:''}</div>${proto('ank','ANK Protocol','text-[var(--primary)]')}${proto('jodi','JODI Protocol','text-[#B85CFF]')}${proto('pannel','PAN Protocol','text-[var(--amber)]')}<button onclick="saveMaster(false)" class="w-full bg-[var(--green)] text-white py-3 rounded-xl font-black text-[10px] uppercase active:scale-95"><i class="fas fa-save mr-1"></i>Save Money Setup</button></div>`;
            const rulesPanel = () => `<div class="space-y-3"><div class="native-card p-4" style="border-color:rgba(42,171,238,0.25);background:rgba(42,171,238,0.04)"><h3 class="text-[12px] font-black text-[var(--primary)] uppercase mb-3"><i class="fas fa-clock mr-1"></i>Time Rules</h3><div class="grid grid-cols-2 gap-2 mb-3"><div><p class="stat-lbl">Day Boundary</p><input id="setup-day-boundary" type="time" value="${tr.dayBoundaryTime||'06:00'}" class="native-input text-[12px]"></div><div><p class="stat-lbl">Scrape Min</p><input id="setup-scrape-interval" type="number" value="${sc.scrapeIntervalMinutes||5}" class="native-input text-[12px]"></div></div><div class="grid gap-2">${sw('setup-accept-before',tr.acceptBeforeMarketTime!==false,'Accept Before Time','Time se pehle accept')}${sw('setup-reject-after',tr.rejectAfterMarketTime!==false,'Reject After Time','Time ke baad reject')}${sw('setup-daily-repeat',tr.dailyRepeatSchedule!==false,'Daily Repeat','Same time daily repeat')}${sw('setup-stage-split',tr.separateOpenCloseStage!==false,'Open / Close Split','Dono stage alag')}</div></div><div class="native-card p-4" style="border-color:rgba(250,199,72,0.25);background:rgba(250,199,72,0.04)"><h3 class="text-[12px] font-black text-[var(--amber)] uppercase mb-3"><i class="fas fa-magnet mr-1"></i>Scrape Rules</h3><div class="grid grid-cols-2 gap-2 mb-3"><div><p class="stat-lbl">Confirm Count</p><input id="setup-confirm-count" type="number" value="${sc.confirmCount||2}" class="native-input text-[12px]"></div><label class="bg-[var(--surface-light)] border border-[var(--border)] rounded-xl p-3 text-[9px] font-black text-white flex items-center justify-between">Auto Scrape <span class="switch scale-[0.65] m-0"><input id="setup-auto-scrape" type="checkbox" ${sc.autoScrapeEnabled!==false?'checked':''}><span class="slider"></span></span></label><div><p class="stat-lbl">Open Format</p><input id="setup-open-format" value="${sc.openFormatHelper||'123-4'}" class="native-input text-[12px]"></div><div><p class="stat-lbl">Close Format</p><input id="setup-close-format" value="${sc.closeFormatHelper||'123-45-678'}" class="native-input text-[12px]"></div></div>${sw('setup-ignore-old',sc.ignoreOldFullResult!==false,'Ignore Old Full Result','Old close auto skip')}</div><button onclick="saveSetupRulesCompact()" class="w-full bg-[var(--primary)] text-white py-3 rounded-xl font-black text-[10px] uppercase active:scale-95"><i class="fas fa-save mr-1"></i>Save Rules</button></div>`;
            const content = window.setupPanel==='market'?marketPanel():(window.setupPanel==='visible'?visibilityPanel():(window.setupPanel==='money'?moneyPanel():rulesPanel()));
            return `<div class="px-3 py-3 pb-8"><div class="native-card p-4 mb-3" style="border-color:rgba(42,171,238,0.22);background:linear-gradient(135deg,rgba(42,171,238,0.10),rgba(10,15,31,0.96))"><div class="flex items-center justify-between gap-3 mb-3"><div><h2 class="text-white text-[16px] font-black uppercase tracking-wide">Setup Control Center</h2><p class="text-[9px] text-[var(--text-muted)] uppercase tracking-widest">Compact · Individual · Low Scroll</p></div><button onclick="saveMaster(false)" class="bg-[var(--green)] text-white px-3 py-2 rounded-xl font-black text-[9px] uppercase active:scale-95"><i class="fas fa-cloud-arrow-up mr-1"></i>Save</button></div><div class="grid grid-cols-4 gap-2"><div class="stat-box"><p class="stat-lbl">Markets</p><p class="stat-val text-[var(--primary)]">${bm.length}</p></div><div class="stat-box"><p class="stat-lbl">Deleted</p><p class="stat-val text-[var(--rose)]">${deletedMarketsList().length}</p></div><div class="stat-box"><p class="stat-lbl">Boundary</p><p class="stat-val text-[var(--amber)]">${tr.dayBoundaryTime||'06:00'}</p></div><div class="stat-box"><p class="stat-lbl">Target</p><p class="stat-val text-[var(--green)]">₹${dayTgt||0}</p></div></div></div><div class="grid grid-cols-2 gap-2 mb-3">${panelBtn('market','fa-store','Markets','Add / delete')}${panelBtn('visible','fa-toggle-on','Visibility','ANK / JODI / PAN')}${panelBtn('money','fa-coins','Money','Capital / target')}${panelBtn('rules','fa-sliders','Rules','Time / scrape')}</div>${content}</div>`;
        }

'''

def main():
    if not P.exists():
        print('ERROR: flask_app.py not found. Run inside ~/titan-app folder.', file=sys.stderr)
        return 1
    s = P.read_text(encoding='utf-8')
    a = s.find(START)
    b = s.find(END, a if a >= 0 else 0)
    if a < 0 or b < 0:
        print('ERROR: renderSettings markers not found. No changes made.', file=sys.stderr)
        return 1
    bak = P.with_name('flask_app.py.bak_setup_ui')
    if not bak.exists():
        bak.write_text(s, encoding='utf-8')
    P.write_text(s[:a] + NEW + s[b:], encoding='utf-8')
    print('OK: Setup Control Center compact UI applied.')
    print('Backup:', bak)
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
